name: cnn-digit-predictor
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - tensorflow=2.10.0
  - numpy=1.26.4
  - pillow=10.3.0
  # PySimpleGUI 4.60.5 requires special handling from wheel file